name: 'Install dependencies (npm ci)'
description: 'npm install (with GITHUB_TOKEN to run postinstall step)'

runs:
  using: 'composite'
  steps:
    - run: npm ci --prefer-offline --no-audit
      env:
        npm_config_build_from_source: true
      shell: bash
